"""Add image_url to characters table

Revision ID: 35fdad556dad
Revises: e648e0244e84
Create Date: 2024-12-26 18:16:30.182077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35fdad556dad'
down_revision: Union[str, None] = 'e648e0244e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'image_url')
    # ### end Alembic commands ###
